#!/usr/bin/env python
"""
Step 2: Run Model

Time-integrates the ATM spectral model using the preprocessed input files
generated by 01_preprocess.py.

Usage:
    python scripts/02_run_model.py --config config/experiments/my_exp.yaml

Experiment output directory (netCDF + restart .pt files) is created at:
    {experiment_root}/T{zw}L{kmax}_{season}_{heating_name}_{start_year}-{end_year}/

For restarts: set cold_start=false and toffset=<days already run> in the config.
"""

import argparse
import os
import subprocess
import sys

import numpy as np
import pandas as pd
import torch
import yaml


# ---------------------------------------------------------------------------
# Helpers shared with other scripts
# ---------------------------------------------------------------------------

def load_config(path):
    with open(path) as f:
        return yaml.safe_load(f)


def build_grid_params(zw):
    match zw:
        case 42:  return 42, 64, 128, 216
        case 63:  return 63, 96, 192, 324
        case 124: return 124, 188, 376, 648
        case _:   raise ValueError(f"Unsupported zw={zw}.")


def build_preprocess_path(cfg):
    if cfg.get("preprocess_path_override"):
        return cfg["preprocess_path_override"]
    zw, kmax = cfg["zw"], cfg["kmax"]
    season = cfg["season"].upper()
    y0, y1 = cfg["start_year"], cfg["end_year"]
    return os.path.join(cfg["preprocess_root"],
                        f"preprocess__zw_{zw}__kmax_{kmax}_{season}_{y0}-{y1}")


def build_experiment_path(cfg):
    zw, kmax = cfg["zw"], cfg["kmax"]
    season = cfg["season"].upper()
    y0, y1 = cfg["start_year"], cfg["end_year"]
    hname = cfg["heating_name"]
    return os.path.join(cfg["experiment_root"],
                        f"T{zw}L{kmax}_{season}_{hname}_{y0}-{y1}")


# ---------------------------------------------------------------------------
# MultiThread (beta) model runner
# ---------------------------------------------------------------------------

def run_multithreaded_beta(cfg, preprocess_path, datapath):
    """Run the weakly-prescribed-mean (beta) model variant."""
    zw   = cfg["zw"]
    kmax = cfg["kmax"]
    mw, jmax, imax, steps_per_day_default = build_grid_params(zw)
    steps_per_day = cfg.get("steps_per_day") or steps_per_day_default
    toffset  = cfg.get("toffset", 0)
    tl       = cfg["chunk_size_days"]
    ichunk   = cfg["run_length_days"] // tl
    heating_file = cfg.get("heating_file_override") or f"heat.ggrid_{cfg['heating_name']}.pt"

    from subs1_utils import (
        set_spectral_transforms, initialize, bscst, mcoeff, inv_em,
        uv, gradq, nlprod, vortdivspec, diffsn, damp_test,
        explicit, postprocessing, lap_sht
    )

    print(f"  Resolution: zw={zw}, kmax={kmax}, jmax={jmax}, imax={imax}")
    print(f"  Run: {ichunk} chunks × {tl} days = {ichunk*tl} days total")
    print(f"  toffset={toffset} ({'cold start' if toffset == 0 else 'restart'})")

    # Spectral transforms and grid
    cost_lg, wlg, lats, lons, vsht, dsht, disht, dvsht, divsht = \
        set_spectral_transforms(jmax, imax, mw, zw)

    # GPU if available (MPS on Apple Silicon, otherwise CPU)
    if torch.backends.mps.is_available():
        print("  Running on GPU (MPS)")
        device = torch.device("mps")
    else:
        print("  Running on CPU")
        device = torch.device("cpu")

    # Coriolis parameter
    coriolis = np.broadcast_to(
        [(4.0 * np.pi / 86400) * np.sin(lats[j, np.newaxis] * np.pi / 180.0)
         for j in range(jmax)],
        (jmax, imax)
    )

    # Load preprocess files
    print("  Loading preprocess data...")
    temp_newton  = torch.load(os.path.join(preprocess_path, "temp.spectral.pt"),   weights_only=False)
    lnpsclim     = torch.load(os.path.join(preprocess_path, "lnps.spectral.pt"),   weights_only=False)
    tclim_gg     = torch.load(os.path.join(preprocess_path, "tsig.ggrid.pt"),      weights_only=False)
    vortclim_gg  = torch.load(os.path.join(preprocess_path, "vortsig.ggrid.pt"),   weights_only=False)
    divclim_gg   = torch.load(os.path.join(preprocess_path, "divsig.ggrid.pt"),    weights_only=False)
    phismn       = torch.load(os.path.join(preprocess_path, "topog.spectral.pt"),  weights_only=False)
    heat         = torch.load(os.path.join(preprocess_path, heating_file),         weights_only=False)

    divclim  = dsht(divclim_gg)
    vortclim = dsht(vortclim_gg)
    tclim    = dsht(tclim_gg)

    # Vertical structure matrices
    delsig, si, sl, sikap, slkap, cth1, cth2, r1b, r2b = bscst(kmax)
    amtrx, cmtrx, dmtrx = mcoeff(kmax, si, sl, slkap, r1b, r2b, delsig)
    emtrx = inv_em(dmtrx, steps_per_day, kmax, mw, zw)

    # Initialize spectral fields
    def _zeros3(): return torch.zeros((kmax, mw, zw), dtype=torch.complex128)
    def _zeros2(): return torch.zeros((mw, zw), dtype=torch.complex128)

    zmn1, zmn2 = _zeros3(), _zeros3()
    dmn1, dmn2 = _zeros3(), _zeros3()
    tmn1, tmn2 = _zeros3(), _zeros3()
    wmn1, wmn2 = _zeros3(), _zeros3()
    qmn1, qmn2 = _zeros2(), _zeros2()

    if toffset > 0:  # Restart: load saved spectral fields
        print(f"  Loading restart files from {datapath} ...")
        for name, var in [("zmn1", zmn1), ("zmn2", zmn2),
                           ("dmn1", dmn1), ("dmn2", dmn2),
                           ("tmn1", tmn1), ("tmn2", tmn2),
                           ("qmn1", qmn1), ("qmn2", qmn2)]:
            loaded = torch.load(os.path.join(datapath, f"{name}.spectral.pt"), weights_only=False)
            var.copy_(loaded)
    else:  # Cold start
        tmn1, tmn2, zmn3, qmn1, qmn2, qmn3 = \
            initialize(tclim, lnpsclim, kmax, mw, zw, tmn1, tmn2, _zeros3())

    zmn3 = _zeros3()
    dmn3 = _zeros3()
    tmn3 = _zeros3()
    wmn3 = _zeros3()
    qmn3 = _zeros2()

    # Accumulation arrays
    tmnt = torch.zeros((tl, kmax, mw, zw), dtype=torch.complex128)
    zmnt = tmnt.detach().clone()
    dmnt = tmnt.detach().clone()
    wmnt = tmnt.detach().clone()
    qmnt = torch.zeros((tl, mw, zw), dtype=torch.complex128)

    ddtdiv  = _zeros3()
    ddtvort = _zeros3()

    idays = tl * ichunk
    nstep = idays * int(steps_per_day)
    times = pd.date_range(start="1950-01-01", end="2100-01-01", freq="D")

    # ---- Time loop ----
    ii = 0
    savedat   = 0
    daycount  = 0
    total_days = 0

    print(f"  Starting time loop: {nstep} steps ({idays} days)...")
    while ii < nstep:
        ii += 1
        savedat += 1

        zmnt[daycount] += zmn1 / steps_per_day
        dmnt[daycount] += dmn1 / steps_per_day
        tmnt[daycount] += tmn1 / steps_per_day
        qmnt[daycount] += qmn1 / steps_per_day
        wmnt[daycount] += wmn1 / steps_per_day

        if savedat == int(steps_per_day):
            daycount   += 1
            total_days += 1
            print(f"    Day = {total_days + toffset}")

            if daycount == tl:
                times_chunk = times[total_days - tl + toffset : total_days + toffset]
                postprocessing(disht, divsht, zmnt, dmnt, tmnt, qmnt, wmnt,
                               phismn, amtrx, times_chunk, mw, zw,
                               kmax, imax, jmax, sl, lats, lons, tl, datapath)
                # Reset accumulators
                tmnt = torch.zeros((tl, kmax, mw, zw), dtype=torch.complex128)
                zmnt = tmnt.detach().clone()
                dmnt = tmnt.detach().clone()
                wmnt = tmnt.detach().clone()
                qmnt = torch.zeros((tl, mw, zw), dtype=torch.complex128)
                daycount = 0
            savedat = 0

        # Spectral → grid
        vort = disht(zmn2)
        div  = disht(dmn2)
        temp = disht(tmn2)
        qdot = disht(wmn2)
        u, v = uv(divsht, zmn2, dmn2, mw, zw, kmax, imax, jmax)
        dxq, dyq = gradq(divsht, qmn2, mw, zw, imax, jmax)

        # Non-linear products
        a, b, e, ut, vt, ri, wj, cbar, dbar = nlprod(
            u, v, vort, div, temp, dxq, dyq, heat, coriolis,
            delsig, si, sikap, slkap, r1b, r2b, cth1, cth2, cost_lg, kmax, imax, jmax
        )

        # Grid → spectral
        ddtdiv, ddtvort = vortdivspec(vsht, a, b, kmax, mw, zw)
        zmn3 = -ddtvort
        dmn3 = ddtdiv - lap_sht(dsht, e, mw, zw)
        _, ttend = vortdivspec(vsht, ut, vt, kmax, mw, zw)
        tmn3 = -ttend + dsht(ri)
        wmn3 = dsht(wj)
        qmn3 = -dsht(cbar)

        # Diffusion and damping
        zmn3, dmn3, tmn3 = diffsn(zmn1, zmn3, dmn1, dmn3, tmn1, tmn3, mw, zw)
        zmn3, dmn3, tmn3, qmn3 = damp_test(
            zmn1, zmn3, dmn1, dmn3, tmn1, tmn3, qmn1, qmn3,
            tclim, lnpsclim, vortclim, divclim, kmax, mw, zw
        )

        # Time integration
        dt = 86400.0 / steps_per_day
        (zmn1, zmn2, zmn3, dmn1, dmn2, dmn3,
         tmn1, tmn2, tmn3, qmn1, qmn2, qmn3) = explicit(
            dt, amtrx, cmtrx, dmtrx, emtrx,
            zmn1, zmn2, zmn3, dmn1, dmn2, dmn3,
            tmn1, tmn2, tmn3, wmn1, wmn2, wmn3,
            qmn1, qmn2, qmn3, phismn, delsig, kmax, mw, zw
        )

        zmn3 = _zeros3(); dmn3 = _zeros3()
        tmn3 = _zeros3(); wmn3 = _zeros3()
        qmn3 = _zeros2()

    # Save restart files
    print("  Saving restart files...")
    for name, tensor in [("zmn1", zmn1), ("zmn2", zmn2),
                          ("dmn1", dmn1), ("dmn2", dmn2),
                          ("tmn1", tmn1), ("tmn2", tmn2),
                          ("qmn1", qmn1), ("qmn2", qmn2)]:
        torch.save(tensor, os.path.join(datapath, f"{name}.spectral.pt"))
    print("  Done.")


# ---------------------------------------------------------------------------
# Gamma_AC model runner (delegates to existing RunModel.Gamma.py)
# ---------------------------------------------------------------------------

def run_gamma_ac(cfg, preprocess_path, datapath):
    """
    Calls Gamma_AC_Model/RunModel.Gamma.py as a subprocess, passing all
    resolution/chunking/path settings explicitly so the config YAML is the
    single source of truth (RunModel.Gamma.py falls back to its own
    hardcoded defaults only when run standalone without these flags).
    """
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    script = os.path.join(project_root, "Gamma_AC_Model", "RunModel.Gamma.py")

    # Gamma script uses expname as AC_{expstub}, so we strip AC_ prefix if present
    expname = os.path.basename(datapath)
    expstub = expname[3:] if expname.startswith("AC_") else expname

    ichunk  = cfg["run_length_days"] // cfg["chunk_size_days"]
    toffset = cfg.get("toffset", 0)

    cmd = [sys.executable, script,
           "--expname", expstub,
           "--toffset", str(toffset),
           "--ichunk",  str(ichunk),
           "--datapath", datapath,
           "--prepath",  preprocess_path,
           "--zw",   str(cfg["zw"]),
           "--kmax", str(cfg["kmax"]),
           "--tl",   str(cfg["chunk_size_days"])]
    print(f"  Running: {' '.join(cmd)}")
    subprocess.run(cmd, check=True, cwd=os.path.join(project_root, "Gamma_AC_Model"))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="ATM workflow step 2: run model")
    parser.add_argument("--config", required=True, help="Path to YAML config file")
    args = parser.parse_args()

    cfg = load_config(args.config)

    # Build paths
    preprocess_path = build_preprocess_path(cfg)
    datapath        = build_experiment_path(cfg)

    # Validate preprocess dir exists
    if not os.path.isdir(preprocess_path):
        raise FileNotFoundError(
            f"Preprocess directory not found: {preprocess_path}\n"
            "Run 01_preprocess.py first."
        )

    # Create or validate experiment output dir
    cold_start = cfg.get("cold_start", True)
    if cold_start:
        if os.path.isdir(datapath):
            import shutil
            print(f"Cold start: removing existing experiment directory {datapath}")
            shutil.rmtree(datapath)
        os.makedirs(datapath)
        print(f"Created experiment directory: {datapath}")
    else:
        if not os.path.isdir(datapath):
            os.makedirs(datapath)
        print(f"Restart: using experiment directory: {datapath}")

    # Add the right model directory to sys.path
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    model_type   = cfg["model_type"]

    if model_type == "multithreaded":
        sys.path.insert(0, os.path.join(project_root, "MultiThread_Model"))
        subtype = cfg.get("model_subtype", "beta")
        if subtype == "prescribed_mean":
            raise NotImplementedError(
                "prescribed_mean subtype not yet wired up in this script. "
                "Use RunModel.PrescribedMean.ipynb directly."
            )
        print(f"Running MultiThread model (subtype={subtype})...")
        run_multithreaded_beta(cfg, preprocess_path, datapath)

    elif model_type == "gamma_ac":
        sys.path.insert(0, os.path.join(project_root, "Gamma_AC_Model"))
        print("Running Gamma_AC model...")
        run_gamma_ac(cfg, preprocess_path, datapath)

    else:
        raise ValueError(f"Unknown model_type: {model_type}")

    print(f"\nModel run complete. Output in: {datapath}")


if __name__ == "__main__":
    main()
